### ISSUE TITLE
App is crashing in day view and week view

### ISSUE THREAD

**Issue by naveenkumarmallappa** [developerVatsal/MyDynamicCalendarExample#6]
App is crashed on Day view and week view, check below error logs

`FATAL EXCEPTION: main
                                                                                         Process: com.desai.vatsal.mydynamiccalendarexample, PID: 4531
                                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.LinearLayout.setBackgroundColor(int)' on a null object reference
                                                                                             at com.desai.vatsal.mydynamiccalendar.ShowDayViewEventsListAdapter$ShowEventsViewHolder.setDayEvents(ShowDayViewEventsListAdapter.java:132)
                                                                                             at com.desai.vatsal.mydynamiccalendar.ShowDayViewEventsListAdapter$ShowEventsViewHolder.setShowEvents(ShowDayViewEventsListAdapter.java:70)
                                                                                             at com.desai.vatsal.mydynamiccalendar.ShowDayViewEventsListAdapter.onBindViewHolder(ShowDayViewEventsListAdapter.java:174)
                                                                                             at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6279)
                                                                                             at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6312)
                                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5258)
                                                                                             at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5521)
                                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                                                                                             at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                                                                                             at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                                                                                             at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)
                                                                                             at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1488)
                                                                                             at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:585)
                                                                                             at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3506)
                                                                                             at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:2969)
                                                                                             at android.view.View.measure(View.java:18811)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                             at android.view.View.measure(View.java:18811)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                             at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1112)
                                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:632)
                                                                                             at android.view.View.measure(View.java:18811)
                                                                                             at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1283)
                                                                                             at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                             at android.widget.ScrollView.onMeasure(ScrollView.java:340)
                                                                                             at android.view.View.measure(View.java:18811)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                             at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1112)
                                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:632)
                                                                                             at android.view.View.measure(View.java:18811)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                             at android.view.View.measure(View.java:18811)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                             at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                                             at android.view.View.measure(View.java:18811)
                                                                                             at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
                                                                                             at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                                             at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1112)
                                                                                             at android.widget.LinearLayout.onMeasure(LinearLayout.java:632)
                                                                                         	at android.view.V`

**Comment by ghost** [comment]
Hello,
Have you solved the problem because I have the same issue?

Thanks in advance

**Comment by xiegeyang** [comment]
Same issue here!

**Comment by waqarv712** [comment]
Have you sloved the issue because i also have this issue

**Comment by youssefyedes** [comment]
did anyone solved this issue ?

**Comment by naveenkumarmallappa** [comment]
Hi All, 
I think it looks like this library not maintained from the past 2 years. 
I just took this below the library but it not having day and week view.

[https://github.com/SundeepK/CompactCalendarView](https://github.com/SundeepK/CompactCalendarView)
